from _contract_docs import contract_doc_text


# TESTDECOUPLE SL-2 (runtime-core): resolve the runtime's OWN contract docs from
# package-data via importlib.resources, not parents[3]/docs, so this test passes
# standalone in the extracted agent-harness layout.
def _regenesis() -> str:
    return contract_doc_text("phase-loop", "substrate-soak-regenesis.md")


def _report() -> str:
    return contract_doc_text("phase-loop", "substrate-soak-report.md")


def test_regenesis_support_doc_cites_only_supported_surfaces():
    text = _regenesis()
    for token in (
        "phase-loop runtime",
        "codex-phase-loop alias",
        "harness workflow skill packs",
        "collaborator bootstrap docs",
        "runtime boundary docs",
        "substrate manifest docs",
        "bridge fixtures",
        "metadata-only closeout surfaces",
    ):
        assert token in text


def test_regenesis_support_doc_denies_owner_bootstrap_and_direct_writes():
    text = _regenesis().lower()
    for token in (
        "full owner " "dotfiles bootstrap is out of scope",
        "shell profile sourcing is out of scope",
        "ssh setup is out of scope",
        "mcp setup is out of scope",
        "terminal or zellij setup is out of scope",
        "generic 1password setup is out of scope",
        "sibling repository mutation is out of scope",
        "direct regenesis changes are out of scope",
        "direct governed pipeline changes are out of scope",
        "direct portal changes are out of scope",
        "direct greenfield changes are out of scope",
        ".pipeline/** changes are out of scope",
        "raw " "evidence is out of scope",
        "provider " "payloads are out of scope",
        "credentials are out of scope",
        "local environment values are out of scope",
        "legacy .codex/phase-loop/** changes are out of scope",
    ):
        assert token in text
    for forbidden in (
        "must run " "bootstrap.sh",
        "must source " "shell profile",
        "must configure ssh",
        "must configure mcp",
        "must configure zellij",
        "write regenesis",
        "write governed pipeline",
        "write portal",
        "write greenfield",
        "write " ".pipeline",
        "provider " "payload:",
        "credential " "payload",
        "local env " "value",
        "legacy .codex/phase-loop " "write",
    ):
        assert forbidden not in text


def test_substratesoak_report_records_exit_criteria_and_verification():
    text = _report()
    for token in (
        "Fixture matrix covers standalone",
        "Governed Pipeline v25 mirror fixtures can be regenerated by Governed Pipeline",
        "Portal v40 evidence remains metadata-only",
        "ReGenesis v46 docs state supported runtime, skill, fixture, and closeout metadata surfaces",
        "The phase writes no sibling repo",
        ".phase-loop/ remains the authoritative runner state source",
        "IF-0-SUBSTRATESOAK-1",
        "PYTHONPATH=vendor/phase-loop-runtime/src python -m pytest vendor/phase-loop-runtime/tests/test_phase_loop_pipeline_bridge.py -k substratesoak",
        "PYTHONPATH=vendor/phase-loop-runtime/src python -m pytest vendor/phase-loop-runtime/tests/test_phase_loop_substrate_soak_governed.py",
        "PYTHONPATH=vendor/phase-loop-runtime/src python -m pytest vendor/phase-loop-runtime/tests/test_phase_loop_substrate_soak_portal.py",
        "PYTHONPATH=vendor/phase-loop-runtime/src python -m pytest vendor/phase-loop-runtime/tests/test_phase_loop_substrate_soak_docs.py",
    ):
        assert token in text
