"""CS-0.5 -- the `.consiliency/` scaffolder (first-writer).

`phase-loop consiliency-scaffold --repo <path> --archetype <name>` writes a
schema-valid `.consiliency/` layout: a manifest declaring the archetype(s) +
governed-doc allowlist, a contract-version/status artifact, an (initially
empty) interface declaration, and presence-only L0 stubs for the archetype's
required baseline docs.

Design constraints (roadmap CS-0.5):

* **Additive, never destructive.** This module never modifies or deletes
  `.phase-loop/` or `.pipeline/`, and it never overwrites a file that already
  exists -- "first-writer" means the scaffolder only fills gaps. Re-running it
  on an already-scaffolded (or hand-edited) repo is a safe no-op for anything
  present.
* **No fake projections.** Where the required-documents registry marks a doc
  ``l0_stub_allowed: true`` (the common case), the scaffolder writes a minimal
  presence-only stub with an explicit "authored zone" -- honest about being
  unauthored, never a hand-written imitation of real content. Where a doc is
  ``l0_stub_allowed: false`` (``readme``, ``license``, and the ``document``
  archetype's ``document-index``), the scaffolder never invents content: it
  references the file if the repo already has it at the conventional path,
  and otherwise only *declares* the manifest entry, leaving the gap for a
  human -- the CS-0.6 presence gate reports that gap as a WARN finding.
* **Vendored schemas only.** All shapes come from ``consiliency_contract``
  (the published shared contract package); nothing here re-implements or
  copies schema literals.
"""
from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

from .consiliency_layout import (
    ARCHETYPE_IDS,
    MODIFIER_IDS,
    RequiredDocRow,
    compose_required_documents,
    consiliency_root,
    contract_version_status_schema,
    find_consiliency_manifest,
    installed_contract_version,
    interface_declaration_schema,
    interfaces_path,
    manifest_path,
    manifest_schema,
    status_path,
)
from .models import utc_now

#: Docs the scaffolder generates as REAL minimal artifacts (not stubs) -- their
#: content is true/current information (installed package version, an empty
#: declared-edge set), never a placeholder standing in for unauthored prose.
_MACHINE_REAL_IDS = ("contract-version-status", "interface-declaration")

#: Well-known repo-root filenames for the handful of baseline docs that have
#: an obvious conventional home. Everything else is scaffolded under
#: `.consiliency/docs/<id>.md`, a namespace that can never collide with a
#: repo's own doc layout.
_ROOT_CONVENTION_PATHS: dict[str, str] = {
    "readme": "README.md",
    "license": "LICENSE",
    "contributing": "CONTRIBUTING.md",
    "changelog": "CHANGELOG.md",
    "codeowners": "CODEOWNERS",
}

_SLUG_RE = re.compile(r"[^a-z0-9_.-]+")


def _slugify(name: str) -> str:
    slug = _SLUG_RE.sub("-", name.strip().lower()).strip("-.")
    if not slug or not slug[0].isalnum():
        slug = f"repo-{slug}" if slug else "repo"
    return slug


def _default_branch(repo: Path) -> str:
    try:
        ref = subprocess.check_output(
            ["git", "-C", str(repo), "symbolic-ref", "--short", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if ref:
            return ref
    except Exception:
        pass
    return "main"


def _doc_target_path(row: RequiredDocRow) -> str:
    if row.id in _MACHINE_REAL_IDS:
        return f".consiliency/{'status.json' if row.id == 'contract-version-status' else 'interfaces.json'}"
    if row.id in _ROOT_CONVENTION_PATHS:
        return _ROOT_CONVENTION_PATHS[row.id]
    return f".consiliency/docs/{row.id}.md"


def _stub_body(row: RequiredDocRow) -> str:
    title = row.id.replace("-", " ").title()
    note = row.l0_note or (
        f"This is an L0 presence-only stub. Its existence satisfies the Consiliency "
        f"`{row.id}` document surface at maturity `presence-only` -- it declares that "
        "this surface is tracked, not that its content has been authored."
    )
    if row.id == "codeowners":
        return (
            f"# Generated by: phase-loop consiliency-scaffold (doc-id={row.id}, maturity=presence-only)\n"
            f"# {note}\n"
            "# consiliency:authored-zone:start\n"
            "# TODO: author real CODEOWNERS entries.\n"
            "# consiliency:authored-zone:end\n"
        )
    return (
        f"<!-- consiliency:generated-by=phase-loop consiliency-scaffold -->\n"
        f"<!-- consiliency:doc-id={row.id} -->\n"
        f"<!-- consiliency:maturity=presence-only -->\n\n"
        f"# {title}\n\n"
        f"{note}\n\n"
        "<!-- consiliency:authored-zone:start -->\n"
        "TODO: author this document's real content.\n"
        "<!-- consiliency:authored-zone:end -->\n"
    )


@dataclass(frozen=True)
class ScaffoldResult:
    repo: Path
    dry_run: bool
    manifest_path: Path
    manifest_written: bool
    created_paths: tuple[str, ...]
    referenced_paths: tuple[str, ...]
    declared_missing_paths: tuple[str, ...]
    already_present: bool

    def to_json(self) -> dict[str, Any]:
        return {
            "repo": str(self.repo),
            "dry_run": self.dry_run,
            "manifest_path": str(self.manifest_path),
            "manifest_written": self.manifest_written,
            "created_paths": list(self.created_paths),
            "referenced_paths": list(self.referenced_paths),
            "declared_missing_paths": list(self.declared_missing_paths),
            "already_present": self.already_present,
        }


class ScaffoldError(ValueError):
    """Bad scaffold input (unknown archetype/modifier, baseline-only + archetypes, ...)."""


def scaffold(
    repo: str | Path,
    *,
    mode: str,
    archetypes: tuple[str, ...] = (),
    modifiers: tuple[str, ...] = (),
    repo_id: str | None = None,
    display_name: str | None = None,
    dry_run: bool = False,
) -> ScaffoldResult:
    repo = Path(repo)
    if mode not in ("baseline-only", "archetyped"):
        raise ScaffoldError(f"invalid mode: {mode!r} (expected 'baseline-only' or 'archetyped')")
    if mode == "baseline-only" and (archetypes or modifiers):
        raise ScaffoldError("baseline-only mode does not accept --archetype/--modifier")
    if mode == "archetyped" and not archetypes:
        raise ScaffoldError("archetyped mode requires at least one --archetype")
    unknown_archetypes = sorted(set(archetypes) - set(ARCHETYPE_IDS))
    if unknown_archetypes:
        raise ScaffoldError(f"unknown archetype(s): {unknown_archetypes}; known: {list(ARCHETYPE_IDS)}")
    unknown_modifiers = sorted(set(modifiers) - set(MODIFIER_IDS))
    if unknown_modifiers:
        raise ScaffoldError(f"unknown modifier(s): {unknown_modifiers}; known: {list(MODIFIER_IDS)}")

    existing_manifest = find_consiliency_manifest(repo)
    already_present = existing_manifest is not None
    target_manifest_path = manifest_path(repo)

    rows = compose_required_documents(mode=mode, archetypes=archetypes, modifiers=modifiers)

    created: list[str] = []
    referenced: list[str] = []
    declared_missing: list[str] = []
    documents: list[dict[str, Any]] = []

    for row in sorted(rows, key=lambda r: r.id):
        rel_path = _doc_target_path(row)
        abs_path = repo / rel_path
        documents.append(
            {
                "id": row.id,
                "class": row.doc_class,
                "path": rel_path,
                "maturity": "presence-only",
                "target_level": "L0",
                "required": row.required,
            }
        )
        if abs_path.exists():
            referenced.append(rel_path)
            continue
        if row.id in _MACHINE_REAL_IDS or row.l0_stub_allowed:
            created.append(rel_path)
            if not dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                if row.id == "contract-version-status":
                    abs_path.write_text(
                        json.dumps(_status_payload(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
                    )
                elif row.id == "interface-declaration":
                    abs_path.write_text(
                        json.dumps(_interfaces_payload(repo_id or _slugify(repo.name)), indent=2, sort_keys=True) + "\n",
                        encoding="utf-8",
                    )
                else:
                    abs_path.write_text(_stub_body(row), encoding="utf-8")
        else:
            # l0_stub_allowed: false and nothing on disk -- do NOT fabricate.
            # Declared in the manifest; the presence gate reports the gap.
            declared_missing.append(rel_path)

    manifest = {
        "schema": "consiliency.manifest.v1",
        "contract_version": installed_contract_version(),
        "repo": {
            "id": repo_id or _slugify(repo.name),
            "display_name": display_name or repo.name,
            "default_branch": _default_branch(repo),
        },
        "declaration": (
            {"mode": "baseline-only"}
            if mode == "baseline-only"
            else {
                "mode": "archetyped",
                "archetypes": sorted(archetypes),
                **({"modifiers": sorted(modifiers)} if modifiers else {}),
            }
        ),
        "documents": documents,
        "interfaces": ".consiliency/interfaces.json",
    }
    Draft202012Validator(manifest_schema()).validate(manifest)

    manifest_written = False
    if not already_present and not dry_run:
        target_manifest_path.parent.mkdir(parents=True, exist_ok=True)
        target_manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        manifest_written = True
    elif not already_present:
        manifest_written = True  # what WOULD be written, for dry-run reporting

    return ScaffoldResult(
        repo=repo,
        dry_run=dry_run,
        manifest_path=target_manifest_path,
        manifest_written=manifest_written,
        created_paths=tuple(created),
        referenced_paths=tuple(referenced),
        declared_missing_paths=tuple(declared_missing),
        already_present=already_present,
    )


def _status_payload() -> dict[str, Any]:
    version = installed_contract_version()
    return {
        "schema": "consiliency.contract_version_status.v1",
        "package": {"name": "consiliency-contract", "version": version},
        "repo_contract_version": version,
        "compatibility": "compatible",
        "maturity": "presence-only",
        "checked_at": utc_now(),
        "evidence": [],
    }


def _interfaces_payload(repo_id: str) -> dict[str, Any]:
    return {
        "schema": "consiliency.interface_declaration.v1",
        "repo_id": repo_id,
        "realized_edges": [],
        "promised_edges": [],
    }


# Defensive self-checks -- the schemas ARE the contract; validate our own
# generated shapes against them so a drift in this module fails loud in tests
# rather than silently shipping a manifest the gates can't parse.
def _validate_generated_artifacts(repo: Path) -> None:
    status_file = status_path(repo)
    if status_file.is_file():
        Draft202012Validator(contract_version_status_schema()).validate(json.loads(status_file.read_text(encoding="utf-8")))
    interfaces_file = interfaces_path(repo)
    if interfaces_file.is_file():
        Draft202012Validator(interface_declaration_schema()).validate(json.loads(interfaces_file.read_text(encoding="utf-8")))
